### ISSUE TITLE
Rossz explode

### ISSUE THREAD

**Issue by beamkiller** [passatgt/wc-dpd-weblabel-export#2]
Hello,

A következő sorban az explode-nál rossz karakter van megadva. Jelenleg csak az első rendelés kerül be a CSV fájlba.

`$orderids = array_map('intval', explode(',', $_GET['order_id']));`

módosítani kéne erre:
``$orderids = array_map('intval', explode('|', $_GET['order_id']));``

**Comment by passatgt** [comment]
Köszi!
